### ISSUE TITLE
My blackmarlin suddenly stopped generating fens

### ISSUE THREAD

**Issue by sana2024** [jnlt3/blackmarlin#235]
Hi,
i have downloaded blackmarlin-linux-64 from the website 10 months ago and deployed it on hugging face, it worked fine till yesterday, i gave it a fen and it converted it to moves, but it suddenly stopped working, is there a way for me to fix it??

this is my code:
 
<img width="1249" alt="Screenshot 2024-02-24 at 12 36 22 AM" src="https://github.com/jnlt3/blackmarlin/assets/53705282/f65d675d-e13e-4a0d-a75d-d2caf10cef80">

and this is what the result looks like

<img width="1320" alt="Screenshot 2024-02-24 at 12 38 30 AM" src="https://github.com/jnlt3/blackmarlin/assets/53705282/73dd1dea-1eea-4cfe-8aa4-0b87bed07e8d">

Where it should be like:
<img width="1360" alt="Screenshot 2024-02-24 at 12 39 57 AM" src="https://github.com/jnlt3/blackmarlin/assets/53705282/25e3111f-7b87-4b1e-9dd6-5d6c132aa976">

**Comment by jnlt3** [comment]
Hello,

It seems you have limited search depth to 2 inside of the python code? That would explain why it stops so early. 
If you would like to limit the time it takes to search, I'd instead suggest placing a node limit.

If Multi PV (Calculating multiple best moves) is going to prove useful, please let me know either on this issue or another one and I will take the time to implement it.
